extends:
  - eslint:recommended
  - standard
plugins:
  - standard
env:
  es6: true
  node: true
  mocha: true
rules:
  camelcase: 0
  no-var: 2
  prefer-const: 2
  no-else-return: "error"
  no-useless-concat: "error"
  prefer-template: "error"
  no-process-env: "error"
