port: PORT
host: HOST
mailRecipient: MAIL_RECIPIENT
database:
  url: MONGODB_URI
api:
  baseUrl: API_BASE_URL
auth:
  token:
    secret: TOKEN_SECRET
  adminUsers: ADMIN_USERS
auth0:
    callbackUrl: AUTH0_CALLBACK_URL
    domain: AUTH0_DOMAIN
    clientId: AUTH0_CLIENT_ID
sendgrid:
  user: SENDGRID_USERNAME
  pass: SENDGRID_PASSWORD
admin:
  users: ADMIN_USERS
