port: '8080'
name: 'Roleando'
host: 'roleando.herokuapp.com'
mailRecipient: 'guuweb@gmail.com'
blogUrl: 'http://historiasdeunhobbit.wordpress.com'
database:
  url: 'mongodb://localhost:27017/roleando'
auth:
  token:
    secret: 'roleandovoy'
    audience: 'roleando.herokuapp.com'
    issuer: 'roleando.herokuapp.com'
    expiresIn: '5d' # expires in 5 days
  refreshToken:
    expiresIn: '30d' # expires in 30 days
  adminUsers: '1'
auth0:
  domain: 'localhost'
  clientId: '12345'
sendgrid:
  user: 'sendgrid_user'
  pass: 'sendgrid_pass'
admin:
  users: 'none'
